name: Run CI checks

on:
  pull_request:
  push:
    branches:
      master

jobs:
  lint_and_test:
    name: Make sure it's all peachy :3
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install packages
        run: npm install
      - name: Check TS
        run: npm tun ts-check
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Headpat yourself ^_^
        run: echo "Great job <3"
